In [28]:
import numpy as np
import pandas as pd

In [16]:
data = pd.read_csv('train.csv')
test_data =pd.read_csv('test.csv')

In [17]:
#defining the target(y) and features(X)
y=data.SalePrice
features=['MSSubClass','YearBuilt','YrSold','LotArea','OverallQual']
test_X=test_data[features]
X=data[features]
print(X)

      MSSubClass  YearBuilt  YrSold  LotArea  OverallQual
0             60       2003    2008     8450            7
1             20       1976    2007     9600            6
2             60       2001    2008    11250            7
3             70       1915    2006     9550            7
4             60       2000    2008    14260            8
...          ...        ...     ...      ...          ...
1455          60       1999    2007     7917            6
1456          20       1978    2010    13175            6
1457          70       1941    2010     9042            7
1458          20       1950    2010     9717            5
1459          20       1965    2008     9937            5

[1460 rows x 5 columns]

In [18]:
#splitintg the data
from sklearn.model_selection import train_test_split
train_X,val_X,train_y,val_y=train_test_split(X,y,random_state=0)

In [19]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error
def get_mae(max_leaf_nodes,train_X,val_X,train_y,val_y):
    data_model=DecisionTreeRegressor(max_leaf_nodes=max_leaf_nodes,random_state=0)
    data_model.fit(train_X,train_y)
    pred=data_model.predict(val_X)
    mae=mean_absolute_error(val_y,pred)
    return mae

In [21]:
candidate_leaf_values=[5,50,100,250,500,1000,2500,5000]

score={leaf_value:get_mae(leaf_value,train_X,val_X,train_y,val_y) for leaf_value in candidate_leaf_values}
print(min(score,key=score.get))

50

In [22]:
data_model=DecisionTreeRegressor(max_leaf_nodes=50,random_state=0)
data_model.fit(X,y)
predictions =data_model.predict(test_X)

In [23]:
submission=test_data[["Id"]]
submission

        Id
0     1461
1     1462
2     1463
3     1464
4     1465
...    ...
1454  2915
1455  2916
1456  2917
1457  2918
1458  2919

[1459 rows x 1 columns]

In [26]:
submission["SalePrice"] = predictions
submission

C:\Users\Hp\AppData\Local\Temp\ipykernel_26460\467029946.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  submission["SalePrice"] = predictions

        Id      SalePrice
0     1461  148149.157143
1     1462  186596.018519
2     1463  148149.157143
3     1464  182547.263158
4     1465  213036.000000
...    ...            ...
1454  2915   90055.357143
1455  2916   90055.357143
1456  2917  148149.157143
1457  2918  148149.157143
1458  2919  205476.985294

[1459 rows x 2 columns]

In [27]:
submission.to_csv('submission.csv',index=None)
pd.read_csv("submission.csv")

        Id      SalePrice
0     1461  148149.157143
1     1462  186596.018519
2     1463  148149.157143
3     1464  182547.263158
4     1465  213036.000000
...    ...            ...
1454  2915   90055.357143
1455  2916   90055.357143
1456  2917  148149.157143
1457  2918  148149.157143
1458  2919  205476.985294

[1459 rows x 2 columns]